name: CI

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
        matrix: 
          target: [wasm32-unknown-unknown, x86_64-unknown-linux-gnu]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install rust
      uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ matrix.target }}
        components: "clippy, rustfmt"
    - name: Check formatting
      run: cargo fmt --check
    - name: Check lints
      run: cargo clippy --all-targets --all-features
    - name: Run tests
      run: cargo test --all-targets --all-features
